name: svgaplayer_3
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 3.0.0
homepage: https://github.com/bear3z/SVGAPlayer-Flutter

environment:
  sdk: '>=3.3.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  http: ^1.2.2
  path_drawing: ^1.0.0
  archive: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
